services:
  ais-catcher:
    container_name: ais-catcher
    image: ghcr.io/samuelgturner/ais-catcher-control:edge
    restart: unless-stopped
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - ais-config:/config
    ports:
      - 8100:8100
      - 8118:8118
    command:
      - -E
      - /config/config.json
      - 0.0.0.0:8118
    device_cgroup_rules:
      - 'c 189:* rmw'

volumes:
  ais-config:
