---
name: media_service

services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    ports:
      - 7359:7359/udp # autodiscovery
      - 8096:8096
    networks:
      reverse_proxy:
    volumes:
      - jellyfin:/config
      - ${PATH_DATA}:/data
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      # JELLYFIN_PublishedServerUrl: `media.${DOMAIN_PUBLIC}` #optional
    labels:
      kop.namespace: kop
      traefik.enable: true
      traefik.http.routers.jellyfin.entrypoints: websecure
      traefik.http.routers.jellyfin.tls: true
      traefik.http.routers.jellyfin.tls.certresolver: letsencrypt
      traefik.http.routers.jellyfin.rule: Host(`media.${DOMAIN_PUBLIC}`)
      traefik.http.routers.jellyfin.service: jellyfin-svc
      traefik.http.services.jellyfin-svc.loadbalancer.server.port: 8096

networks:
  reverse_proxy:
    external: true

volumes:
  jellyfin:


