---
name: arr

services:
  gluetun:
    container_name: gluetun
    image: qmcgaw/gluetun:v3
    restart: unless-stopped
    ports:
    - 6789:6789 # nzbget
    - 6881:6881
    - 6881:6881/udp
    - 7878:7878 # Radarr
    - 8085:8085 # qbittorrent
    - 8989:8989 # Sonarr
    - 9696:9696 # Prowlarr
    networks:
      gluetun:
    volumes:
    - gluetun:/gluetun
    environment:
      TZ: ${TZ}
      VPN_SERVICE_PROVIDER: nordvpn
      VPN_TYPE: wireguard
      WIREGUARD_PRIVATE_KEY: ${WIREGUARD_PRIVATE_KEY}
      SERVER_COUNTRIES: ${WIREGUARD_COUNTRY}
      UPDATER_PERIOD: 24h
    cap_add:
    - NET_ADMIN
    devices:
    - /dev/net/tun:/dev/net/tun
    healthcheck:
      test: ping -c 1 www.google.com || exit 1
      interval: 600s
      timeout: 10s
      retries: 5
      start_period: 30s
      start_interval: 5s
    hostname: gluetun

  qbittorrent:
    container_name: qbittorrent
    image: lscr.io/linuxserver/qbittorrent
    restart: unless-stopped
    depends_on:
      gluetun:
        condition: service_healthy
        restart: true
    volumes:
    - qbittorrent:/config
    - /data/arr:/data
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      WEBUI_PORT: 8085
      TORRENTING_PORT: ${TORRENTING_PORT}
    network_mode: service:gluetun

  nzbget:
    container_name: nzbget
    image: lscr.io/linuxserver/nzbget:latest
    restart: unless-stopped
    depends_on:
      gluetun:
        condition: service_healthy
        restart: true
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - nzbget:/config
    - /data/arr:/data
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    network_mode: service:gluetun

  prowlarr:
    container_name: prowlarr
    image: lscr.io/linuxserver/prowlarr:latest
    restart: unless-stopped
    depends_on:
      gluetun:
        condition: service_healthy
        restart: true
    volumes:
    - prowlarr:/config
    - /data/arr:/data
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    network_mode: service:gluetun

  sonarr:
    container_name: sonarr
    image: lscr.io/linuxserver/sonarr:latest
    restart: unless-stopped
    depends_on:
      gluetun:
        condition: service_healthy
        restart: true
    volumes:
    - sonarr:/config
    - /data/arr:/data
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    network_mode: service:gluetun

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    depends_on:
      gluetun:
        condition: service_healthy
        restart: true
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - radarr:/config
    - /data/arr:/data
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    network_mode: service:gluetun

networks:
  gluetun:
    name: gluetun

volumes:
  gluetun:
  qbittorrent:
  nzbget:
  prowlarr:
  sonarr:
  radarr:
