name: template-stack

services:
  
  # Template
  template:
    container_name: Template
    image: hello-world:latest
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    # command:
    # volumes:
    networks:
      reverse_proxy_private:
    # ports:
    environment:
      - TZ=$TZ
    labels:
      traefik.enable: true
      # HTTP Routers
      traefik.http.routers.template.entrypoints: web
      traefik.http.routers.template.rule: Host(`template.${DOMAINNAME}`)
      # Middlewares
      # traefik.http.routers.template.middlewares: chain-oauth@file
      # HTTP Services
      traefik.http.routers.template.service: template-svc
      traefik.http.services.template-svc.loadbalancer.server.port: 9999
 

networks:
  reverse_proxy_private:
    external:
      true
  
  # reverse_proxy_public:
  #   external:
  #     true


