---
docker_apt_release_channel: "stable"
docker_apt_repository: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
docker_daemon_options:
  storage-driver: "overlay2"
