name: HomeServer

networks:
  reverse_proxy_private:
    external: true
    driver_opts:
      com.docker.network.driver.mtu: 1492
  reverse_proxy_public:
    external: true
    driver_opts:
      com.docker.network.driver.mtu: 1492
  docker_socket_proxy:
    external: true
  traefik-kop:
    name: traefik-kop
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1492

include:
  - ais-catcher/docker-compose.yml
  - home-assistant/docker-compose.yml
  - it-tools/docker-compose.yml
  - jellyfin/docker-compose.yml
  # - pagermon/docker-compose.yml
  - reverse-proxy-redis/docker-compose.yml
