name: HomeServer

networks:
  reverse_proxy_private:
    external: true
  reverse_proxy_public:
    external: true
  docker_socket_proxy:
    external: true
  traefik-kop:
    name: traefik-kop
    driver: bridge

include:
  - ais-catcher/docker-compose.yml
  - home-assistant/docker-compose.yml
  - it-tools/docker-compose.yml
  - jellyfin/docker-compose.yml
  # - pagermon/docker-compose.yml
  - reverse-proxy-redis/docker-compose.yml
