services:
  whoami:
    container_name: whoami
    image: traefik/whoami
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    networks:
      reverse_proxy:
    labels:
      traefik.enable: true
      traefik.docker.network: reverse_proxy
      # HTTP Routers
      traefik.http.routers.whoami.rule: Host(`whoami.${ROOT_DOMAIN}`)
      traefik.http.routers.whoami.entrypoints: websecure
      # HTTP Services
      traefik.http.routers.whoami.service: whoami-svc
      traefik.http.services.whoami-svc.loadbalancer.server.port: 80
