services:
  # Pi-hole - DNS Ad Block
  pihole:
    container_name: Pi-hole
    image: pihole/pihole:latest
    restart: unless-stopped
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    hostname: pihole.${DOMAINNAME}
    networks:
      reverse_proxy_private:
        ipv4_address: ${PIHOLE_IP}
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    environment:
      TZ: ${TZ}
      WEBPASSWORD: ${PIHOLE_PASSWORD}
      FTLCONF_LOCAL_IPV4: ${PIHOLE_IP}
    labels:
      traefik.enable: true
      # HTTP Routers
      traefik.http.routers.pihole.entrypoints: web
      traefik.http.routers.pihole.rule: Host(`pihole.${DOMAINNAME}`)
      # Middlewares
      # traefik.http.routers.pihole.middlewares: chain-oauth@file
      # HTTP Services
      traefik.http.routers.pihole.service: pihole-svc
      traefik.http.services.pihole-svc.loadbalancer.server.port: 80
    profiles:
      - prod
    stdin_open: true # docker run -i
    tty: true        # docker run -t
